version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mongodb+srv://admin:admin123@cluster0.yctcrkx.mongodb.net/nestdb?retryWrites=true&w=majority
    dns:
      - 8.8.8.8  # Google DNS
      - 1.1.1.1  # Cloudflare DNS
    restart: unless-stopped